### ISSUE TITLE
Not working - no logs

### ISSUE THREAD

**Issue by baudneo** [crowdsecurity/cs-openresty-bouncer#13]
I can't get this bouncer to work. I have enabled logging via the openresty nginx.conf for error and access logs. I have added LOG_FILE directive to the bouncer config but the log file is never created.

I have no way to debug what is going on with the openresty bouncer, I have tried watching the crowdsec.log file but it offers no clues on what's going on. I have several other bouncers working correctly and this is the last one I need to get working fory Nginx Proxy Manager setup.

How do I get access to any sort of logging for the openresty bouncer?

**Comment by he2ss** [comment]
Hi @baudneo,

Sorry the `LOG_FILE` directive is depracated (we'll remove it from the documentation).
The logs are stored in the nginx error logs.

**Comment by baudneo** [comment]
Hi, I have turned all the logging options on in nginx conf and the openresty nginx.conf but no logs are ever output. The bouncer is added to `cscli` but it only registered the time it tried its first request, there is no IP or version. It is not working correctly as far as I can tell. I have openresty and openresty-opm installed and also the lua plugin it asks about when installing. I am running debian 10.

```
 proxmox-iptables  x.x.x.x    ✔️      2022-02-10T10:43:44Z  crowdsec-firewall-bouncer    v0.0.22-debian-pragmatic-f64e94b59a948717c3dc848f9abebb27b5974714
 local-openresty               ✔️      2022-02-10T09:45:52Z
```

### /usr/local/openresty/nginx/conf/nginx.conf
```
#user  nobody;
worker_processes  1;

error_log  logs/or-error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/or-access.log  main;
```
### Contents of openresty log dir `/usr/local/openresty/nginx/logs/`
```
.rw-r--r-- root root   6 B  Thu Feb 10 03:43:44 2022  nginx.pid
.rw-r--r-- root root   0 B  Thu Feb 10 01:46:51 2022  or-access.log
.rw-r--r-- root root   0 B  Thu Feb 10 01:46:51 2022  or-error.log
.rw-r--r-- root root   0 B  Thu Feb 10 01:46:51 2022  or-host.access.log
```
### `nginx.conf` from `/etc/nginx`
```
        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
```
### Contents of nginx log dir
```
.rw-r----- www-data adm   0 B  Wed Dec  1 00:00:01 2021  /var/log/nginx/access.log
.rw-r----- www-data adm   0 B  Fri Nov 26 00:00:01 2021  /var/log/nginx/error.log
```

**Comment by baudneo** [comment]
Hi, any updates? I am still unable to successfully add an openresty bouncer that polls for decisions. It is added just fine but then it never polls the Local API for decisions after it is initially added.

**Comment by baudneo** [comment]
Things are working now.
