### ISSUE TITLE
Support custom install locations

### ISSUE THREAD

**Issue by LePresidente** [crowdsecurity/cs-openresty-bouncer#16]
When installing on docker images like nginx-proxy-manager these folders need to be overwritten and the relevant files patched as well

NGINX_CONF_DIR="/usr/local/openresty/nginx/conf/conf.d/"
LIB_PATH="/usr/local/openresty/lualib/"
CONFIG_PATH="/etc/crowdsec/bouncers/"
DATA_PATH="/var/lib/crowdsec/lua/"

**Comment by he2ss** [comment]
PR was merged
