### ISSUE TITLE
Custom logging option?

### ISSUE THREAD

**Issue by baudneo** [crowdsecurity/cs-openresty-bouncer#17]
Is there a way to have the bouncer output it's logs to its own file instead of openresty defualt access/error logs?

I have integrated the bouncer into Nginx Proxy Manager but monitoring the openresty logs for crowdsec info is not the best.

That or certain messages logged to its own log file? Like when it takes action and info on when it pulls decisions? At the moment it's mixed in with all sorts of other information.

Thanks.

**Comment by he2ss** [comment]
Hi @baudneo,

We decide to use [ngx.log](https://github.com/openresty/lua-nginx-module#ngxlog) because of performances issues (see https://github.com/cloudflare/lua-resty-logger-socket/issues/33).
