### ISSUE TITLE
crowdsec.lua error . nginx version: openresty/1.21.4.1

### ISSUE THREAD

**Issue by andyoulovexy** [crowdsecurity/cs-openresty-bouncer#36]
2023/11/02 21:09:27 [error] 29979#29979: [lua] crowdsec.lua:48: init(): error loading captcha plugin: no recaptcha site key provided, can't use recaptcha
2023/11/02 21:09:27 [alert] 29979#29979: [lua] init_by_lua:11: [Crowdsec] Initialisation done
2023/11/02 21:09:32 [error] 29984#29984: *3 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/crowdsec.lua:161: attempt to index local 'ip_network_address' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/openresty/lualib/crowdsec.lua: in function 'item_to_string'
        /usr/local/openresty/lualib/crowdsec.lua:395: in function 'allowIp'
        /usr/local/openresty/lualib/crowdsec.lua:457: in function 'Allow'

**Comment by LaurenceJJones** [comment]
Solved via https://github.com/crowdsecurity/cs-openresty-bouncer/pull/37

We wasnt not ignoring sockets
