### ISSUE TITLE
Openresty infront of mailcow

### ISSUE THREAD

**Issue by pittbull** [crowdsecurity/cs-openresty-bouncer#48]
I am running a rig with a local api and a remote mailserver (based on [mailcow](https://mailcow.email))

I have crowdsec installed on the remote server and hooked up to my api with a firewall bouncer, but I would like to use captcha on the remote server. I have installed the docker version of crowdsecurity/openresty, but I am struggelig as to where and how implement this in the process.

Is it possible to run openresty infront of another nginx both in separate docker images?

//Thomas

**Comment by LaurenceJJones** [comment]
Yes you should be able to put this infront of a Nginx you would have to mount a custom default server configuration into openresty so all requests sent to the server are proxy pass to the other nginx.

**Comment by pittbull** [comment]
So in my own words: Traffic should hit openresty nginx, and then be proxy-passed to mailcow?

**Comment by LaurenceJJones** [comment]
> So in my own words: Traffic should hit openresty nginx, and then be proxy-passed to mailcow?
> 
> I am trying to wrap my head around this information ([mailcow behind proxy](https://docs.mailcow.email/post_installation/reverse-proxy/r_p/)), and [this](https://github.com/crowdsecurity/cs-openresty-bouncer/tree/main/docker) documentation on your docker image - but I am not able to understand where to do what.
> 
> Care to share some insight?

Not to sound completely rude but we cant walk you through how to configure a reverse proxy as that is not our goal.

Maybe you can try joining our [discord](https://discord.gg/crowdsec) and the community over there might be able to help.

**Comment by pittbull** [comment]
Fair point.
