### ISSUE TITLE
Update to 1.0.3 breaks ingress-nginx bouncer

### ISSUE THREAD

**Issue by hofalk** [crowdsecurity/cs-openresty-bouncer#55]
There is a missing double quote at the end of the line, which breaks our ingress-nginx bouncer:

https://github.com/crowdsecurity/cs-openresty-bouncer/blob/5e8ff635cb77444f1ab7aa39e4af53253571982d/ingress-nginx/main.lua#L5

Came in with the latest bounce to 1.0.3

**Comment by LaurenceJJones** [comment]
Going to find best to way to republish the containers

**Comment by LaurenceJJones** [comment]
The only way to force an update is publish another release, `1.0.4` should fix it and will be on container platforms soon
